name: Publish package to the Maven Central Repository
on:
  release:
    types: [created]

env:
  GRIDDB_SERVER_NAME: "myCluster"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v3
        with:
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-passphrase: ${{ secrets.PASSPHRASE }}
      - name: Create and run GridDB server
        run: . .github/workflows/function.sh && run_griddb_server
      - name: Turn off firewall
        run: . .github/workflows/function.sh && firewall_disable
      - name: Build package Jdbc Driver
        run: . .github/workflows/function.sh && build_jdbc
      - name: Run sample JDBC
        run: . .github/workflows/function.sh && run_sample
      - name: Publish to the Maven Central Repository
        run: echo "mlem" #mvn clean --batch-mode deploy
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
